language: python

jobs:
  include:
    - os: linux
      python: 3.7
    - os: linux
      python: 3.9
    - os: linux
      python: '3.10'
    - os: linux
      python: '3.11'
    - os: osx
      osx_image: xcode14.1
      name: "macOS"
      language: generic

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 --version ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip3 install -U pip ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python --version ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install -U pip ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip3 install . ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install . ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m tests ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if [ "$TRAVIS_PYTHON_VERSION" != "3.8" ]; then python -m tests ; fi ; fi
